name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main   # only push images when main is updated

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image from subfolder
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/login-project:latest \
            ./Flask-Web-App-Tutorial

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-project:latest

      - name: Trigger Webhook on EC2 for Deployment
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{"redeploy": "true"}'

            
